FROM node:22

RUN apt-get update && \
    apt-get install -y python3 python3-pip supervisor && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir --break-system-packages -r requirements.txt

WORKDIR /app/hina/app/frontend
RUN yarn install --ignore-platform

WORKDIR /app

COPY supervisor.conf /etc/supervisor/conf.d/supervisor.conf

EXPOSE 8000 3000

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisor.conf"]
